# Generated by Django 6.0.4 on 2026-05-06 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='fine_amount',
            new_name='current_fine',
        ),
    ]
