# Generated by Django 6.0.4 on 2026-05-06 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_fine_amount_rental_current_fine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='current_fine',
            new_name='fine_amount',
        ),
    ]
