# Generated by Django 6.0.4 on 2026-05-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_current_fine_rental_fine_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='fine_amount',
            new_name='current_fine',
        ),
    ]
