# Generated by Django 5.1.6 on 2026-05-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_cart_id_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='rent_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
    ]
