# Generated by Django 6.0.4 on 2026-05-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_cart_id_alter_cartitem_id_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='current_fine',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='rental',
            name='rent_fee',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
